import Hero from "@/components/Hero";
import AvailableTutors from "@/components/AvailableTutors";
import WhyChooseAndHowItWorks from "@/components/WhyChooseAndHowItWorks";

export const dynamic = 'force-dynamic';

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Hero />
      <AvailableTutors />
      <WhyChooseAndHowItWorks />
    </div>
  );
}


